obj-m += example_mutex_1.o
obj-m += example_mutex_2.o

PWD := $(CURDIR)

all:

	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean :

	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean